# generated by datamodel-codegen:
#   filename:  https://ftc-events.firstinspires.org/swagger/v2.0/swagger.json
#   timestamp: 2026-01-03T16:29:10+00:00

from __future__ import annotations

from typing import Any, Literal, TypeAlias, TypedDict

from typing_extensions import NotRequired


class AdvancementPointsModel(TypedDict):
    team: NotRequired[int]
    points: NotRequired[list[float]]


class AllianceModelVersion2(TypedDict):
    number: NotRequired[int]
    name: NotRequired[str]
    captain: NotRequired[int]
    captainDisplay: NotRequired[str]
    round1: NotRequired[int]
    round1Display: NotRequired[str]
    round2: NotRequired[int]
    round2Display: NotRequired[str]
    round3: NotRequired[int]
    backup: NotRequired[int]
    backupReplaced: NotRequired[int]


class AllianceScore2020(TypedDict):
    adjust: NotRequired[int]
    dcPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcTowerLow: NotRequired[int]
    dcTowerMid: NotRequired[int]
    dcTowerHigh: NotRequired[int]
    navigated1: NotRequired[bool]
    navigated2: NotRequired[bool]
    wobbleDelivered1: NotRequired[bool]
    wobbleDelivered2: NotRequired[bool]
    autoTowerLow: NotRequired[int]
    autoTowerMid: NotRequired[int]
    autoTowerHigh: NotRequired[int]
    autoTowerPoints: NotRequired[int]
    autoPowerShotLeft: NotRequired[bool]
    autoPowerShotCenter: NotRequired[bool]
    autoPowerShotRight: NotRequired[bool]
    autoPowerShotPoints: NotRequired[int]
    wobbleRings1: NotRequired[int]
    wobbleRings2: NotRequired[int]
    wobbleEnd1: NotRequired[int]
    wobbleEnd2: NotRequired[int]
    wobbleEndPoints: NotRequired[int]
    wobbleRingPoints: NotRequired[int]
    autoWobblePoints: NotRequired[int]
    endPowerShotLeft: NotRequired[bool]
    endPowerShotCenter: NotRequired[bool]
    endPowerShotRight: NotRequired[bool]
    endPowerShotPoints: NotRequired[int]
    penaltyPoints: NotRequired[int]
    majorPenalties: NotRequired[int]
    minorPenalties: NotRequired[int]
    navigationPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    totalPoints: NotRequired[int]


class AllianceSelectionModelVersion2(TypedDict):
    alliances: NotRequired[list[AllianceModelVersion2]]
    count: NotRequired[int]


ApiAdvancementStatus: TypeAlias = Literal[
    'NULL', 'FIRST', 'ALREADY_ADVANCING', 'ADVANCING_ABOVE', 'INELIGIBLE'
]


class ApiIndexModel(TypedDict):
    name: NotRequired[str]
    apiVersion: NotRequired[str]
    serviceMainifestName: NotRequired[str]
    serviceMainifestVersion: NotRequired[str]
    codePackageName: NotRequired[str]
    codePackageVersion: NotRequired[str]
    status: NotRequired[str]
    currentSeason: NotRequired[int]
    maxSeason: NotRequired[int]


ArtifactType: TypeAlias = Literal['NONE', 'PURPLE', 'GREEN']


AutoLocation: TypeAlias = Literal['NONE', 'OBSERVATION_ZONE', 'ASCENT']


AutoNavigatedStatus: TypeAlias = Literal[
    'NONE',
    'IN_STORAGE',
    'COMPLETELY_IN_STORAGE',
    'IN_WAREHOUSE',
    'COMPLETELY_IN_WAREHOUSE',
]


AutoNavigation: TypeAlias = Literal['NONE', 'SUBSTATION_TERMINAL', 'SIGNAL_ZONE']


class AwardAssignmentModel(TypedDict):
    awardId: NotRequired[int]
    teamId: NotRequired[int]
    teamProfileId: NotRequired[int]
    eventId: NotRequired[int]
    eventDivisionId: NotRequired[int]
    eventCode: NotRequired[str]
    name: NotRequired[str]
    series: NotRequired[int]
    teamNumber: NotRequired[int]
    schoolName: NotRequired[str]
    fullTeamName: NotRequired[str]
    person: NotRequired[str]


class AwardsModel(TypedDict):
    awards: NotRequired[list[AwardAssignmentModel]]


BarcodeElement: TypeAlias = Literal['DUCK', 'TEAM_SHIPPING_ELEMENT']


class Coordinate(TypedDict):
    x: NotRequired[float]
    y: NotRequired[float]
    z: NotRequired[float]
    m: NotRequired[float]
    coordinateValue: NotRequired[Coordinate]
    isValid: NotRequired[bool]


class CoordinateEqualityComparer(TypedDict):
    pass


DecodeTeleopBaseLocation: TypeAlias = Literal['NONE', 'PARTIAL', 'FULL']


Dimension: TypeAlias = Literal[
    'Point', 'Curve', 'Surface', 'Collapse', 'Dontcare', 'True', 'False'
]


EndGameLocation: TypeAlias = Literal['NONE', 'BACKSTAGE', 'RIGGING']


EndgameParkedStatus: TypeAlias = Literal[
    'NONE', 'IN_WAREHOUSE', 'COMPLETELY_IN_WAREHOUSE'
]


class Envelope(TypedDict):
    isNull: NotRequired[bool]
    width: NotRequired[float]
    height: NotRequired[float]
    diameter: NotRequired[float]
    minX: NotRequired[float]
    maxX: NotRequired[float]
    minY: NotRequired[float]
    maxY: NotRequired[float]
    area: NotRequired[float]
    minExtent: NotRequired[float]
    maxExtent: NotRequired[float]
    centre: NotRequired[Coordinate]


FieldSide: TypeAlias = Literal['SCORING_SIDE', 'AUDIENCE_SIDE']


FTCEventLevel: TypeAlias = Literal[
    'PRACTICE', 'QUALIFICATION', 'SEMIFINAL', 'FINAL', 'PLAYOFF', 'OTHER'
]


class GeometryOverlay(TypedDict):
    pass


JunctionElement: TypeAlias = Literal[
    'MY_CONE',
    'OTHER_CONE',
    'MY_R1_BEACON',
    'MY_R2_BEACON',
    'OTHER_R1_BEACON',
    'OTHER_R2_BEACON',
]


class LeagueMemberListModel(TypedDict):
    members: NotRequired[list[int]]


class MatchResultTeamModelVersion2(TypedDict):
    teamNumber: NotRequired[int]
    station: NotRequired[str]
    dq: NotRequired[bool]
    onField: NotRequired[bool]


OgcGeometryType: TypeAlias = Literal[
    'Point',
    'LineString',
    'Polygon',
    'MultiPoint',
    'MultiLineString',
    'MultiPolygon',
    'GeometryCollection',
    'CircularString',
    'CompoundCurve',
    'CurvePolygon',
    'MultiCurve',
    'MultiSurface',
    'Curve',
    'Surface',
    'PolyhedralSurface',
    'TIN',
]


Ordinates: TypeAlias = Literal[
    'None',
    'X',
    'Y',
    'XY',
    'Z',
    'XYZ',
    'Spatial4',
    'Spatial5',
    'Spatial6',
    'Spatial7',
    'Spatial8',
    'Spatial9',
    'Spatial10',
    'Spatial11',
    'Spatial12',
    'Spatial13',
    'Spatial14',
    'Spatial15',
    'Spatial16',
    'AllSpatialOrdinates',
    'M',
    'XYM',
    'XYZM',
    'Measure2',
    'Measure3',
    'Measure4',
    'Measure5',
    'Measure6',
    'Measure7',
    'Measure8',
    'Measure9',
    'Measure10',
    'Measure11',
    'Measure12',
    'Measure13',
    'Measure14',
    'Measure15',
    'Measure16',
    'AllMeasureOrdinates',
    'AllOrdinates',
]


PrecisionModels: TypeAlias = Literal['Floating', 'FloatingSingle', 'Fixed']


class RegionalAdvancementModel(TypedDict):
    rcmpEventCode: NotRequired[str]
    regionCode: NotRequired[str]
    totalSlots: NotRequired[int]
    fcmpReserved: NotRequired[int]


class ScheduledMatchTeamModelVersion2(TypedDict):
    teamNumber: NotRequired[int]
    displayTeamNumber: NotRequired[str]
    station: NotRequired[str]
    team: NotRequired[str]
    teamName: NotRequired[str]
    surrogate: NotRequired[bool]
    noShow: NotRequired[bool]


class ScheduleHybridModelTeamVersion2(TypedDict):
    teamNumber: NotRequired[int]
    displayTeamNumber: NotRequired[str]
    station: NotRequired[str]
    surrogate: NotRequired[bool]
    noShow: NotRequired[bool]
    dq: NotRequired[bool]
    onField: NotRequired[bool]
    teamName: NotRequired[str]


class ScoreDetailAllianceModel2020(TypedDict):
    adjust: NotRequired[int]
    dcPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcTowerLow: NotRequired[int]
    dcTowerMid: NotRequired[int]
    dcTowerHigh: NotRequired[int]
    navigated1: NotRequired[bool]
    navigated2: NotRequired[bool]
    wobbleDelivered1: NotRequired[bool]
    wobbleDelivered2: NotRequired[bool]
    autoTowerLow: NotRequired[int]
    autoTowerMid: NotRequired[int]
    autoTowerHigh: NotRequired[int]
    autoTowerPoints: NotRequired[int]
    autoPowerShotLeft: NotRequired[bool]
    autoPowerShotCenter: NotRequired[bool]
    autoPowerShotRight: NotRequired[bool]
    autoPowerShotPoints: NotRequired[int]
    wobbleRings1: NotRequired[int]
    wobbleRings2: NotRequired[int]
    wobbleEnd1: NotRequired[int]
    wobbleEnd2: NotRequired[int]
    wobbleEndPoints: NotRequired[int]
    wobbleRingPoints: NotRequired[int]
    autoWobblePoints: NotRequired[int]
    endPowerShotLeft: NotRequired[bool]
    endPowerShotCenter: NotRequired[bool]
    endPowerShotRight: NotRequired[bool]
    endPowerShotPoints: NotRequired[int]
    penaltyPoints: NotRequired[int]
    majorPenalties: NotRequired[int]
    minorPenalties: NotRequired[int]
    navigationPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    totalPoints: NotRequired[int]
    alliance: NotRequired[str]
    team: NotRequired[int]


class ScoreDetailAllianceModel2021(TypedDict):
    alliance: NotRequired[str]
    barcodeElement1: NotRequired[BarcodeElement]
    barcodeElement2: NotRequired[BarcodeElement]
    carousel: NotRequired[bool]
    autoNavigated1: NotRequired[AutoNavigatedStatus]
    autoNavigated2: NotRequired[AutoNavigatedStatus]
    autoBonus1: NotRequired[bool]
    autoBonus2: NotRequired[bool]
    autoStorageFreight: NotRequired[int]
    autoFreight1: NotRequired[int]
    autoFreight2: NotRequired[int]
    autoFreight3: NotRequired[int]
    driverControlledStorageFreight: NotRequired[int]
    driverControlledFreight1: NotRequired[int]
    driverControlledFreight2: NotRequired[int]
    driverControlledFreight3: NotRequired[int]
    sharedFreight: NotRequired[int]
    endgameDelivered: NotRequired[int]
    allianceBalanced: NotRequired[bool]
    sharedUnbalanced: NotRequired[bool]
    endgameParked1: NotRequired[EndgameParkedStatus]
    endgameParked2: NotRequired[EndgameParkedStatus]
    capped: NotRequired[int]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    carouselPoints: NotRequired[int]
    autoNavigationPoints: NotRequired[int]
    autoFreightPoints: NotRequired[int]
    autoBonusPoints: NotRequired[int]
    driverControlledAllianceHubPoints: NotRequired[int]
    driverControlledSharedHubPoints: NotRequired[int]
    driverControlledStoragePoints: NotRequired[int]
    endgameDeliveryPoints: NotRequired[int]
    allianceBalancedPoints: NotRequired[int]
    sharedUnbalancedPoints: NotRequired[int]
    endgameParkingPoints: NotRequired[int]
    cappingPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    driverControlledPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPoints: NotRequired[int]
    totalPoints: NotRequired[int]


class ScoreDetailAllianceModel2022(TypedDict):
    sideOfField: NotRequired[FieldSide]
    initSignalSleeve1: NotRequired[bool]
    initSignalSleeve2: NotRequired[bool]
    robot1Auto: NotRequired[AutoNavigation]
    robot2Auto: NotRequired[AutoNavigation]
    autoTerminal: NotRequired[int]
    autoJunctions: NotRequired[list[list[list[JunctionElement]]]]
    dcJunctions: NotRequired[list[list[list[JunctionElement]]]]
    dcTerminalNear: NotRequired[int]
    dcTerminalFar: NotRequired[int]
    egNavigated1: NotRequired[bool]
    egNavigated2: NotRequired[bool]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    autoNavigationPoints: NotRequired[int]
    signalBonusPoints: NotRequired[int]
    autoJunctionConePoints: NotRequired[int]
    autoTerminalConePoints: NotRequired[int]
    dcJunctionConePoints: NotRequired[int]
    dcTerminalConePoints: NotRequired[int]
    ownershipPoints: NotRequired[int]
    circuitPoints: NotRequired[int]
    egNavigationPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPointsCommitted: NotRequired[int]
    prePenaltyTotal: NotRequired[int]
    autoJunctionCones: NotRequired[list[int]]
    dcJunctionCones: NotRequired[list[int]]
    beacons: NotRequired[int]
    ownedJunctions: NotRequired[int]
    circuit: NotRequired[bool]
    totalPoints: NotRequired[int]
    alliance: NotRequired[str]
    team: NotRequired[int]


class ScoreDetailAllianceModel2023(TypedDict):
    initTeamProp1: NotRequired[bool]
    initTeamProp2: NotRequired[bool]
    robot1Auto: NotRequired[bool]
    robot2Auto: NotRequired[bool]
    spikeMarkPixel1: NotRequired[bool]
    spikeMarkPixel2: NotRequired[bool]
    targetBackdropPixel1: NotRequired[bool]
    targetBackdropPixel2: NotRequired[bool]
    autoBackdrop: NotRequired[int]
    autoBackstage: NotRequired[int]
    dcBackdrop: NotRequired[int]
    dcBackstage: NotRequired[int]
    mosaics: NotRequired[int]
    maxSetLine: NotRequired[int]
    egRobot1: NotRequired[EndGameLocation]
    egRobot2: NotRequired[EndGameLocation]
    drone1: NotRequired[int]
    drone2: NotRequired[int]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    autoNavigatingPoints: NotRequired[int]
    autoRandomizationPoints: NotRequired[int]
    autoBackstagePoints: NotRequired[int]
    autoBackdropPoints: NotRequired[int]
    dcBackdropPoints: NotRequired[int]
    dcBackstagePoints: NotRequired[int]
    mosaicPoints: NotRequired[int]
    setBonusPoints: NotRequired[int]
    egLocationPoints: NotRequired[int]
    egDronePoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPointsCommitted: NotRequired[int]
    prePenaltyTotal: NotRequired[int]
    totalPoints: NotRequired[int]
    alliance: NotRequired[str]
    team: NotRequired[int]


class ScoreDetailAllianceModel2025(TypedDict):
    autoClassifiedArtifacts: NotRequired[int]
    autoOverflowArtifacts: NotRequired[int]
    autoClassifierState: NotRequired[list[ArtifactType]]
    robot1Auto: NotRequired[bool]
    robot2Auto: NotRequired[bool]
    autoLeavePoints: NotRequired[int]
    autoArtifactPoints: NotRequired[int]
    autoPatternPoints: NotRequired[int]
    teleopClassifiedArtifacts: NotRequired[int]
    teleopOverflowArtifacts: NotRequired[int]
    teleopDepotArtifacts: NotRequired[int]
    teleopClassifierState: NotRequired[list[ArtifactType]]
    robot1Teleop: NotRequired[DecodeTeleopBaseLocation]
    robot2Teleop: NotRequired[DecodeTeleopBaseLocation]
    teleopArtifactPoints: NotRequired[int]
    teleopDepotPoints: NotRequired[int]
    teleopPatternPoints: NotRequired[int]
    teleopBasePoints: NotRequired[int]
    autoPoints: NotRequired[int]
    teleopPoints: NotRequired[int]
    foulPointsCommitted: NotRequired[int]
    preFoulTotal: NotRequired[int]
    movementRP: NotRequired[bool]
    goalRP: NotRequired[bool]
    patternRP: NotRequired[bool]
    totalPoints: NotRequired[int]
    majorFouls: NotRequired[int]
    minorFouls: NotRequired[int]
    alliance: NotRequired[str]
    team: NotRequired[int]


class ScoreDetailModel2020(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2020]]


class ScoreDetailModel2021(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2021]]


class ScoreDetailModel2022(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2022]]


class ScoreDetailModel2023(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2023]]


class ScoreDetailModel2025(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2025]]


class ScoreDetailModelSinglePlayer2020(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchNumber: NotRequired[int]
    teamNumber: NotRequired[int]
    scores: NotRequired[AllianceScore2020]


class ScoreDetailSinglePlayer2021(TypedDict):
    barcodeElement: NotRequired[BarcodeElement]
    carousel: NotRequired[bool]
    autoNavigated: NotRequired[AutoNavigatedStatus]
    autoBonus: NotRequired[bool]
    autoStorageFreight: NotRequired[int]
    autoFreight1: NotRequired[int]
    autoFreight2: NotRequired[int]
    autoFreight3: NotRequired[int]
    driverControlledStorageFreight: NotRequired[int]
    driverControlledFreight1: NotRequired[int]
    driverControlledFreight2: NotRequired[int]
    driverControlledFreight3: NotRequired[int]
    endgameDelivered: NotRequired[int]
    allianceBalanced: NotRequired[bool]
    endgameParked: NotRequired[EndgameParkedStatus]
    capped: NotRequired[int]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    carouselPoints: NotRequired[int]
    autoNavigationPoints: NotRequired[int]
    autoFreightPoints: NotRequired[int]
    autoBonusPoints: NotRequired[int]
    driverControlledAllianceHubPoints: NotRequired[int]
    driverControlledStoragePoints: NotRequired[int]
    endgameDeliveryPoints: NotRequired[int]
    allianceBalancedPoints: NotRequired[int]
    endgameParkingPoints: NotRequired[int]
    cappingPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    driverControlledPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPoints: NotRequired[int]
    totalPoints: NotRequired[int]


class ScoreDetailSinglePlayer2022(TypedDict):
    initSignalSleeve: NotRequired[bool]
    robotAuto: NotRequired[AutoNavigation]
    autoTerminal: NotRequired[int]
    autoJunctions: NotRequired[list[list[list[JunctionElement]]]]
    dcJunctions: NotRequired[list[list[list[JunctionElement]]]]
    dcTerminal: NotRequired[int]
    egNavigated: NotRequired[bool]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    autoNavigationPoints: NotRequired[int]
    signalBonusPoints: NotRequired[int]
    autoJunctionConePoints: NotRequired[int]
    autoTerminalConePoints: NotRequired[int]
    dcJunctionConePoints: NotRequired[int]
    dcTerminalConePoints: NotRequired[int]
    ownershipPoints: NotRequired[int]
    circuitPoints: NotRequired[int]
    egNavigationPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPointsCommitted: NotRequired[int]
    prePenaltyTotal: NotRequired[int]
    autoJunctionCones: NotRequired[list[int]]
    dcJunctionCones: NotRequired[list[int]]
    beacons: NotRequired[int]
    ownedJunctions: NotRequired[int]
    circuit: NotRequired[bool]
    totalPoints: NotRequired[int]


class ScoreDetailSinglePlayer2023(TypedDict):
    initTeamProp: NotRequired[bool]
    robotAuto: NotRequired[bool]
    spikeMarkPixel: NotRequired[bool]
    targetBackdropPixel: NotRequired[bool]
    autoBackdrop: NotRequired[int]
    autoBackstage: NotRequired[int]
    dcBackdrop: NotRequired[int]
    dcBackstage: NotRequired[int]
    mosaics: NotRequired[int]
    maxSetLine: NotRequired[int]
    egRobot: NotRequired[EndGameLocation]
    drone: NotRequired[int]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    autoNavigatingPoints: NotRequired[int]
    autoRandomizationPoints: NotRequired[int]
    autoBackstagePoints: NotRequired[int]
    autoBackdropPoints: NotRequired[int]
    dcBackdropPoints: NotRequired[int]
    dcBackstagePoints: NotRequired[int]
    mosaicPoints: NotRequired[int]
    setBonusPoints: NotRequired[int]
    egLocationPoints: NotRequired[int]
    egDronePoints: NotRequired[int]
    autoPoints: NotRequired[int]
    dcPoints: NotRequired[int]
    endgamePoints: NotRequired[int]
    penaltyPointsCommitted: NotRequired[int]
    prePenaltyTotal: NotRequired[int]
    totalPoints: NotRequired[int]


class SeasonAwardsModel(TypedDict):
    awardId: NotRequired[int]
    name: NotRequired[str]
    description: NotRequired[str]
    forPerson: NotRequired[bool]


class SeasonLeagueModelVersion2(TypedDict):
    region: NotRequired[str]
    code: NotRequired[str]
    name: NotRequired[str]
    remote: NotRequired[bool]
    parentLeagueCode: NotRequired[str]
    parentLeagueName: NotRequired[str]
    location: NotRequired[str]


class SeasonSummaryModelChampionship(TypedDict):
    name: NotRequired[str]
    startDate: NotRequired[str]
    location: NotRequired[str]


class SeasonTeamModelVersion2(TypedDict):
    teamNumber: NotRequired[int]
    displayTeamNumber: NotRequired[str]
    teamId: NotRequired[int]
    teamProfileId: NotRequired[int]
    nameFull: NotRequired[str]
    nameShort: NotRequired[str]
    schoolName: NotRequired[str]
    city: NotRequired[str]
    stateProv: NotRequired[str]
    country: NotRequired[str]
    website: NotRequired[str]
    rookieYear: NotRequired[int]
    robotName: NotRequired[str]
    districtCode: NotRequired[str]
    homeCMP: NotRequired[str]
    homeRegion: NotRequired[str]
    displayLocation: NotRequired[str]


SelectionResult: TypeAlias = Literal['ACCEPT', 'DECLINE', 'REMOVE', 'CAPTAIN']


Stone: TypeAlias = Literal['NONE', 'STONE', 'SKYSTONE']


class TeamRankingModel(TypedDict):
    rank: NotRequired[int]
    teamNumber: NotRequired[int]
    displayTeamNumber: NotRequired[str]
    teamName: NotRequired[str]
    sortOrder1: NotRequired[float]
    sortOrder2: NotRequired[float]
    sortOrder3: NotRequired[float]
    sortOrder4: NotRequired[float]
    sortOrder5: NotRequired[float]
    sortOrder6: NotRequired[float]
    wins: NotRequired[int]
    losses: NotRequired[int]
    ties: NotRequired[int]
    qualAverage: NotRequired[float]
    dq: NotRequired[int]
    matchesPlayed: NotRequired[int]
    matchesCounted: NotRequired[int]


TeleopLocation: TypeAlias = Literal[
    'NONE', 'OBSERVATION_ZONE', 'ASCENT_1', 'ASCENT_2', 'ASCENT_3'
]


class AdvancementSlot(TypedDict):
    team: NotRequired[int]
    teamId: NotRequired[int]
    teamProfileId: NotRequired[int]
    teamInternalId: NotRequired[str]
    displayTeam: NotRequired[str]
    slot: NotRequired[int]
    criteria: NotRequired[str]
    declined: NotRequired[bool]
    status: NotRequired[ApiAdvancementStatus]


class AdvancementSourceModel(TypedDict):
    advancedFrom: NotRequired[str]
    advancedFromRegion: NotRequired[str]
    slots: NotRequired[int]
    reserveSlots: NotRequired[int]
    advancement: NotRequired[list[AdvancementSlot]]


class CoordinateSequence(TypedDict):
    dimension: NotRequired[int]
    measures: NotRequired[int]
    spatial: NotRequired[int]
    ordinates: NotRequired[Ordinates]
    hasZ: NotRequired[bool]
    hasM: NotRequired[bool]
    zOrdinateIndex: NotRequired[int]
    mOrdinateIndex: NotRequired[int]
    first: NotRequired[Coordinate]
    last: NotRequired[Coordinate]
    count: NotRequired[int]


class CoordinateSequenceFactory(TypedDict):
    ordinates: NotRequired[Ordinates]


class EventRankingsModel(TypedDict):
    rankings: NotRequired[list[TeamRankingModel]]


class MatchResultModelVersion2(TypedDict):
    actualStartTime: NotRequired[str]
    description: NotRequired[str]
    tournamentLevel: NotRequired[str]
    series: NotRequired[int]
    matchNumber: NotRequired[int]
    scoreRedFinal: NotRequired[int]
    scoreRedFoul: NotRequired[int]
    scoreRedAuto: NotRequired[int]
    scoreBlueFinal: NotRequired[int]
    scoreBlueFoul: NotRequired[int]
    scoreBlueAuto: NotRequired[int]
    postResultTime: NotRequired[str]
    teams: NotRequired[list[MatchResultTeamModelVersion2]]
    modifiedOn: NotRequired[str]


class PrecisionModel(TypedDict):
    isFloating: NotRequired[bool]
    maximumSignificantDigits: NotRequired[int]
    scale: NotRequired[float]
    gridSize: NotRequired[float]
    precisionModelType: NotRequired[PrecisionModels]


class ScheduledMatchModelVersion2(TypedDict):
    description: NotRequired[str]
    field: NotRequired[str]
    tournamentLevel: NotRequired[str]
    startTime: NotRequired[str]
    series: NotRequired[int]
    matchNumber: NotRequired[int]
    teams: NotRequired[list[ScheduledMatchTeamModelVersion2]]
    modifiedOn: NotRequired[str]


class ScheduleHybridModelVersion2(TypedDict):
    description: NotRequired[str]
    tournamentLevel: NotRequired[str]
    series: NotRequired[int]
    matchNumber: NotRequired[int]
    startTime: NotRequired[str]
    actualStartTime: NotRequired[str]
    postResultTime: NotRequired[str]
    scoreRedFinal: NotRequired[int]
    scoreRedFoul: NotRequired[int]
    scoreRedAuto: NotRequired[int]
    scoreBlueFinal: NotRequired[int]
    scoreBlueFoul: NotRequired[int]
    scoreBlueAuto: NotRequired[int]
    scoreBlueDriveControlled: NotRequired[int]
    scoreBlueEndgame: NotRequired[int]
    redWins: NotRequired[bool]
    blueWins: NotRequired[bool]
    teams: NotRequired[list[ScheduleHybridModelTeamVersion2]]


class ScoreDetailAllianceModel2024(TypedDict):
    robot1Auto: NotRequired[AutoLocation]
    robot2Auto: NotRequired[AutoLocation]
    autoSampleNet: NotRequired[int]
    autoSampleLow: NotRequired[int]
    autoSampleHigh: NotRequired[int]
    autoSpecimenLow: NotRequired[int]
    autoSpecimenHigh: NotRequired[int]
    teleopSampleNet: NotRequired[int]
    teleopSampleLow: NotRequired[int]
    teleopSampleHigh: NotRequired[int]
    teleopSpecimenLow: NotRequired[int]
    teleopSpecimenHigh: NotRequired[int]
    robot1Teleop: NotRequired[TeleopLocation]
    robot2Teleop: NotRequired[TeleopLocation]
    minorFouls: NotRequired[int]
    majorFouls: NotRequired[int]
    autoSamplePoints: NotRequired[int]
    autoSpecimenPoints: NotRequired[int]
    teleopSamplePoints: NotRequired[int]
    teleopSpecimenPoints: NotRequired[int]
    teleopParkPoints: NotRequired[int]
    teleopAscentPoints: NotRequired[int]
    autoPoints: NotRequired[int]
    teleopPoints: NotRequired[int]
    endGamePoints: NotRequired[int]
    foulPointsCommitted: NotRequired[int]
    preFoulTotal: NotRequired[int]
    totalPoints: NotRequired[int]
    alliance: NotRequired[str]
    team: NotRequired[int]


class ScoreDetailModel2024(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailAllianceModel2024]]


class ScoreDetailModelAlliance2019(TypedDict):
    alliance: NotRequired[str]
    robot1Navigated: NotRequired[bool]
    robot1Parked: NotRequired[bool]
    robot1CapstoneLevel: NotRequired[int]
    robot2Navigated: NotRequired[bool]
    robot2Parked: NotRequired[bool]
    robot2CapstoneLevel: NotRequired[int]
    autoStones: NotRequired[list[Stone]]
    autoDelivered: NotRequired[int]
    autoReturned: NotRequired[int]
    firstReturnedIsSkystone: NotRequired[bool]
    autoPlaced: NotRequired[int]
    foundationRepositioned: NotRequired[bool]
    foundationMoved: NotRequired[bool]
    driverControlledDelivered: NotRequired[int]
    driverControlledReturned: NotRequired[int]
    driverControlledPlaced: NotRequired[int]
    tallestSkyscraper: NotRequired[int]
    autoDeliveryPoints: NotRequired[int]
    autoPlacedPoints: NotRequired[int]
    autonomousPoints: NotRequired[int]
    repositionedPoints: NotRequired[int]
    navigationPoints: NotRequired[int]
    driverControlledDeliveryPoints: NotRequired[int]
    driverControlledPlacedPoints: NotRequired[int]
    skyscraperBonusPoints: NotRequired[int]
    capstonePoints: NotRequired[int]
    driverControlledPoints: NotRequired[int]
    parkingPoints: NotRequired[int]
    endGamePoints: NotRequired[int]
    minorPenalties: NotRequired[int]
    majorPenalties: NotRequired[int]
    penaltyPoints: NotRequired[int]
    totalPoints: NotRequired[int]


class ScoreDetailModelSinglePlayer2021(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    teamNumber: NotRequired[int]
    scores: NotRequired[ScoreDetailSinglePlayer2021]


class ScoreDetailModelSinglePlayer2022(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    teamNumber: NotRequired[int]
    scores: NotRequired[ScoreDetailSinglePlayer2022]


class ScoreDetailModelSinglePlayer2023(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchNumber: NotRequired[int]
    randomization: NotRequired[int]
    teamNumber: NotRequired[int]
    scores: NotRequired[ScoreDetailSinglePlayer2023]


class SeasonAwardListingsModel(TypedDict):
    awards: NotRequired[list[SeasonAwardsModel]]


class SeasonLeagueListingsModelVersion2(TypedDict):
    leagues: NotRequired[list[SeasonLeagueModelVersion2]]
    leagueCount: NotRequired[int]


class SeasonSummaryModelVersion2(TypedDict):
    eventCount: NotRequired[int]
    gameName: NotRequired[str]
    kickoff: NotRequired[str]
    rookieStart: NotRequired[int]
    teamCount: NotRequired[int]
    frcChampionships: NotRequired[list[SeasonSummaryModelChampionship]]


class SeasonTeamListingsModelVersion2(TypedDict):
    teams: NotRequired[list[SeasonTeamModelVersion2]]
    teamCountTotal: NotRequired[int]
    teamCountPage: NotRequired[int]
    pageCurrent: NotRequired[int]
    pageTotal: NotRequired[int]


class SelectionModel(TypedDict):
    index: NotRequired[int]
    team: NotRequired[int]
    result: NotRequired[SelectionResult]


class AdvancementModel(TypedDict):
    advancesTo: NotRequired[str]
    slots: NotRequired[int]
    fcmpReserved: NotRequired[int]
    advancement: NotRequired[list[AdvancementSlot]]


class AllianceSelectionDetailModel(TypedDict):
    selections: NotRequired[list[SelectionModel]]
    count: NotRequired[int]


class EventMatchResultsModelVersion2(TypedDict):
    matches: NotRequired[list[MatchResultModelVersion2]]


class EventScheduleHybridModelVersion2(TypedDict):
    schedule: NotRequired[list[ScheduleHybridModelVersion2]]


class EventScheduleModelVersion2(TypedDict):
    schedule: NotRequired[list[ScheduledMatchModelVersion2]]


class NtsGeometryServices(TypedDict):
    geometryOverlay: NotRequired[GeometryOverlay]
    coordinateEqualityComparer: NotRequired[CoordinateEqualityComparer]
    defaultSRID: NotRequired[int]
    defaultCoordinateSequenceFactory: NotRequired[CoordinateSequenceFactory]
    defaultPrecisionModel: NotRequired[PrecisionModel]


class ScoreDetailModel2019(TypedDict):
    matchLevel: NotRequired[FTCEventLevel]
    matchSeries: NotRequired[int]
    matchNumber: NotRequired[int]
    alliances: NotRequired[list[ScoreDetailModelAlliance2019]]


class GeometryFactory(TypedDict):
    precisionModel: NotRequired[PrecisionModel]
    coordinateSequenceFactory: NotRequired[CoordinateSequenceFactory]
    srid: NotRequired[int]
    geometryServices: NotRequired[NtsGeometryServices]


class MatchScoresModel(TypedDict):
    matchScores: NotRequired[
        list[
            ScoreDetailModel2019
            | ScoreDetailModel2020
            | ScoreDetailModelSinglePlayer2020
            | ScoreDetailModel2021
            | ScoreDetailModelSinglePlayer2021
            | ScoreDetailModel2022
            | ScoreDetailModelSinglePlayer2022
            | ScoreDetailModel2023
            | ScoreDetailModelSinglePlayer2023
            | ScoreDetailModel2024
            | ScoreDetailModel2025
        ]
    ]


class Geometry(TypedDict):
    factory: NotRequired[GeometryFactory]
    userData: NotRequired[Any]
    srid: NotRequired[int]
    geometryType: NotRequired[str]
    ogcGeometryType: NotRequired[OgcGeometryType]
    precisionModel: NotRequired[PrecisionModel]
    coordinate: NotRequired[Coordinate]
    coordinates: NotRequired[list[Coordinate]]
    numPoints: NotRequired[int]
    numGeometries: NotRequired[int]
    isSimple: NotRequired[bool]
    isValid: NotRequired[bool]
    isEmpty: NotRequired[bool]
    area: NotRequired[float]
    length: NotRequired[float]
    centroid: NotRequired[Point]
    interiorPoint: NotRequired[Point]
    pointOnSurface: NotRequired[Point]
    dimension: NotRequired[Dimension]
    boundary: NotRequired[Geometry]
    boundaryDimension: NotRequired[Dimension]
    envelope: NotRequired[Geometry]
    envelopeInternal: NotRequired[Envelope]
    isRectangle: NotRequired[bool]


class Point(TypedDict):
    factory: NotRequired[GeometryFactory]
    userData: NotRequired[Any]
    srid: NotRequired[int]
    precisionModel: NotRequired[PrecisionModel]
    numGeometries: NotRequired[int]
    isSimple: NotRequired[bool]
    isValid: NotRequired[bool]
    area: NotRequired[float]
    length: NotRequired[float]
    centroid: NotRequired[Point]
    interiorPoint: NotRequired[Point]
    pointOnSurface: NotRequired[Point]
    envelope: NotRequired[Geometry]
    envelopeInternal: NotRequired[Envelope]
    isRectangle: NotRequired[bool]
    coordinateSequence: NotRequired[CoordinateSequence]
    coordinates: NotRequired[list[Coordinate]]
    numPoints: NotRequired[int]
    isEmpty: NotRequired[bool]
    dimension: NotRequired[Dimension]
    boundaryDimension: NotRequired[Dimension]
    x: NotRequired[float]
    y: NotRequired[float]
    coordinate: NotRequired[Coordinate]
    geometryType: NotRequired[str]
    ogcGeometryType: NotRequired[OgcGeometryType]
    boundary: NotRequired[Geometry]
    z: NotRequired[float]
    m: NotRequired[float]


class SeasonEventListingsModelVersion2(TypedDict):
    events: NotRequired[list[SeasonEventModelVersion2]]
    eventCount: NotRequired[int]


class SeasonEventModelVersion2(TypedDict):
    eventId: NotRequired[str]
    code: NotRequired[str]
    divisionCode: NotRequired[str]
    name: NotRequired[str]
    remote: NotRequired[bool]
    hybrid: NotRequired[bool]
    fieldCount: NotRequired[int]
    published: NotRequired[bool]
    type: NotRequired[str]
    typeName: NotRequired[str]
    regionCode: NotRequired[str]
    leagueCode: NotRequired[str]
    districtCode: NotRequired[str]
    venue: NotRequired[str]
    address: NotRequired[str]
    city: NotRequired[str]
    stateprov: NotRequired[str]
    country: NotRequired[str]
    website: NotRequired[str]
    liveStreamUrl: NotRequired[str]
    coordinates: NotRequired[Point]
    webcasts: NotRequired[list[str]]
    timezone: NotRequired[str]
    dateStart: NotRequired[str]
    dateEnd: NotRequired[str]
